-- Seleciona o banco de dados
USE intuitivecare_db;

-- CRIAÇÃO DAS TABELAS AUXILIARES

-- Tabela temporária para carga inicial dos demonstrativos (sem FK)
CREATE TABLE IF NOT EXISTS demonstrativos_stage (
    DATA DATE,
    REG_ANS VARCHAR(20),
    CD_CONTA_CONTABIL VARCHAR(20),
    DESCRICAO TEXT,
    VL_SALDO_INICIAL DECIMAL(15,2),
    VL_SALDO_FINAL DECIMAL(15,2)
);

-- Tabela para armazenar registros inválidos (sem correspondência em operadoras)
CREATE TABLE IF NOT EXISTS demonstrativos_nao_importados (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATA DATE,
    REG_ANS VARCHAR(20),
    CD_CONTA_CONTABIL VARCHAR(20),
    DESCRICAO TEXT,
    VL_SALDO_INICIAL DECIMAL(15,2),
    VL_SALDO_FINAL DECIMAL(15,2)
);

-- Limpa dados antigos por garantia
TRUNCATE TABLE demonstrativos;
TRUNCATE TABLE operadoras;
TRUNCATE TABLE demonstrativos_nao_importados;

-- IMPORTAÇÃO DAS OPERADORAS
LOAD DATA LOCAL INFILE 'C:/TesteNivelamento/Arquivos/Relatorio_cadop.csv'
INTO TABLE operadoras
CHARACTER SET utf8
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(Registro_ANS, CNPJ, Razao_Social, Nome_Fantasia, Modalidade, Logradouro, Numero, Complemento, Bairro, Cidade, UF, CEP, DDD, Telefone, Fax, Endereco_eletronico, Representante, Cargo_Representante, Regiao_de_Comercializacao, Data_Registro_ANS);

-- IMPORTAÇÃO DOS DEMONSTRATIVOS PARA A TABELA STAGE
-- Repete para cada trimestre

LOAD DATA LOCAL INFILE 'C:/TesteNivelamento/Arquivos/1T2023.csv'
INTO TABLE demonstrativos_stage
CHARACTER SET utf8
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL);


LOAD DATA LOCAL INFILE 'C:/TesteNivelamento/Arquivos/2T2023.csv'
INTO TABLE demonstrativos_stage
CHARACTER SET utf8
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL);


LOAD DATA LOCAL INFILE 'C:/TesteNivelamento/Arquivos/3T2023.csv'
INTO TABLE demonstrativos_stage
CHARACTER SET utf8
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL);


LOAD DATA LOCAL INFILE 'C:/TesteNivelamento/Arquivos/4T2023.csv'
INTO TABLE demonstrativos_stage
CHARACTER SET utf8
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL);


LOAD DATA LOCAL INFILE 'C:/TesteNivelamento/Arquivos/1T2024.csv'
INTO TABLE demonstrativos_stage
CHARACTER SET utf8
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL);


LOAD DATA LOCAL INFILE 'C:/TesteNivelamento/Arquivos/2T2024.csv'
INTO TABLE demonstrativos_stage
CHARACTER SET utf8
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL);


LOAD DATA LOCAL INFILE 'C:/TesteNivelamento/Arquivos/3T2024.csv'
INTO TABLE demonstrativos_stage
CHARACTER SET utf8
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL);


LOAD DATA LOCAL INFILE 'C:/TesteNivelamento/Arquivos/4T2024.csv'
INTO TABLE demonstrativos_stage
CHARACTER SET utf8
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL);

-- INSERE REGISTROS VÁLIDOS
INSERT INTO demonstrativos (DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SELECT DATA, REG_ANS, CD_CONTA_CONTABIL, REPLACE(REPLACE(REPLACE(TRIM(DESCRICAO), '  ', ' '), '  ', ' '), '  ', ' ') AS DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL
FROM demonstrativos_stage
WHERE REG_ANS IN (SELECT Registro_ANS FROM operadoras);

-- INSERE REGISTROS INVÁLIDOS
INSERT INTO demonstrativos_nao_importados (DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL)
SELECT DATA, REG_ANS, CD_CONTA_CONTABIL, REPLACE(REPLACE(REPLACE(TRIM(DESCRICAO), '  ', ' '), '  ', ' '), '  ', ' ') AS DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL
FROM demonstrativos_stage
WHERE REG_ANS NOT IN (SELECT Registro_ANS FROM operadoras);

-- REMOVE A TABELA TEMPORÁRIA
DROP TABLE demonstrativos_stage;

COMMIT;
